#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMSGateway")]
	public partial class DBSMSGatewayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLogCallVTB(LogCallVTB instance);
    partial void UpdateLogCallVTB(LogCallVTB instance);
    partial void DeleteLogCallVTB(LogCallVTB instance);
    partial void InsertTelco(Telco instance);
    partial void UpdateTelco(Telco instance);
    partial void DeleteTelco(Telco instance);
    partial void InsertQueueService(QueueService instance);
    partial void UpdateQueueService(QueueService instance);
    partial void DeleteQueueService(QueueService instance);
    partial void InsertRoute(Route instance);
    partial void UpdateRoute(Route instance);
    partial void DeleteRoute(Route instance);
    partial void InsertRoute_Telco(Route_Telco instance);
    partial void UpdateRoute_Telco(Route_Telco instance);
    partial void DeleteRoute_Telco(Route_Telco instance);
    partial void InsertSubTelco(SubTelco instance);
    partial void UpdateSubTelco(SubTelco instance);
    partial void DeleteSubTelco(SubTelco instance);
    partial void InsertMTQueueReport(MTQueueReport instance);
    partial void UpdateMTQueueReport(MTQueueReport instance);
    partial void DeleteMTQueueReport(MTQueueReport instance);
    partial void InsertMT(MT instance);
    partial void UpdateMT(MT instance);
    partial void DeleteMT(MT instance);
    #endregion
		
		public DBSMSGatewayDataContext() : 
				base(global::LibData.Properties.Settings.Default.SMSGatewayConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBSMSGatewayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSMSGatewayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSMSGatewayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSMSGatewayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LogCallVTB> LogCallVTBs
		{
			get
			{
				return this.GetTable<LogCallVTB>();
			}
		}
		
		public System.Data.Linq.Table<Telco> Telcos
		{
			get
			{
				return this.GetTable<Telco>();
			}
		}
		
		public System.Data.Linq.Table<QueueService> QueueServices
		{
			get
			{
				return this.GetTable<QueueService>();
			}
		}
		
		public System.Data.Linq.Table<Route> Routes
		{
			get
			{
				return this.GetTable<Route>();
			}
		}
		
		public System.Data.Linq.Table<Route_Telco> Route_Telcos
		{
			get
			{
				return this.GetTable<Route_Telco>();
			}
		}
		
		public System.Data.Linq.Table<SubTelco> SubTelcos
		{
			get
			{
				return this.GetTable<SubTelco>();
			}
		}
		
		public System.Data.Linq.Table<MTQueueReport> MTQueueReports
		{
			get
			{
				return this.GetTable<MTQueueReport>();
			}
		}
		
		public System.Data.Linq.Table<MT> MTs
		{
			get
			{
				return this.GetTable<MT>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckSMSID", IsComposable=true)]
		public System.Nullable<int> CheckSMSID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SMSID", DbType="NVarChar(50)")] string sMSID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sMSID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckSMSID_MTQueueReport", IsComposable=true)]
		public System.Nullable<int> CheckSMSID_MTQueueReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SMSID", DbType="NVarChar(50)")] string sMSID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sMSID).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LogCallVTB")]
	public partial class LogCallVTB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Request;
		
		private string _Response;
		
		private System.DateTime _CreateDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRequestChanging(string value);
    partial void OnRequestChanged();
    partial void OnResponseChanging(string value);
    partial void OnResponseChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
		
		public LogCallVTB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Request", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Request
		{
			get
			{
				return this._Request;
			}
			set
			{
				if ((this._Request != value))
				{
					this.OnRequestChanging(value);
					this.SendPropertyChanging();
					this._Request = value;
					this.SendPropertyChanged("Request");
					this.OnRequestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Response", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Response
		{
			get
			{
				return this._Response;
			}
			set
			{
				if ((this._Response != value))
				{
					this.OnResponseChanging(value);
					this.SendPropertyChanging();
					this._Response = value;
					this.SendPropertyChanged("Response");
					this.OnResponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Telco")]
	public partial class Telco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private System.Nullable<int> _Price;
		
		private System.Nullable<int> _ServiceSMS;
		
		private EntitySet<Route_Telco> _Route_Telcos;
		
		private EntitySet<SubTelco> _SubTelcos;
		
		private EntitySet<SubTelco> _SubTelcos1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    partial void OnServiceSMSChanging(System.Nullable<int> value);
    partial void OnServiceSMSChanged();
    #endregion
		
		public Telco()
		{
			this._Route_Telcos = new EntitySet<Route_Telco>(new Action<Route_Telco>(this.attach_Route_Telcos), new Action<Route_Telco>(this.detach_Route_Telcos));
			this._SubTelcos = new EntitySet<SubTelco>(new Action<SubTelco>(this.attach_SubTelcos), new Action<SubTelco>(this.detach_SubTelcos));
			this._SubTelcos1 = new EntitySet<SubTelco>(new Action<SubTelco>(this.attach_SubTelcos1), new Action<SubTelco>(this.detach_SubTelcos1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceSMS", DbType="Int")]
		public System.Nullable<int> ServiceSMS
		{
			get
			{
				return this._ServiceSMS;
			}
			set
			{
				if ((this._ServiceSMS != value))
				{
					this.OnServiceSMSChanging(value);
					this.SendPropertyChanging();
					this._ServiceSMS = value;
					this.SendPropertyChanged("ServiceSMS");
					this.OnServiceSMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Telco_Route_Telco", Storage="_Route_Telcos", ThisKey="Id", OtherKey="IdTelco")]
		public EntitySet<Route_Telco> Route_Telcos
		{
			get
			{
				return this._Route_Telcos;
			}
			set
			{
				this._Route_Telcos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Telco_SubTelco", Storage="_SubTelcos", ThisKey="Id", OtherKey="IdTelco")]
		public EntitySet<SubTelco> SubTelcos
		{
			get
			{
				return this._SubTelcos;
			}
			set
			{
				this._SubTelcos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Telco_SubTelco1", Storage="_SubTelcos1", ThisKey="Id", OtherKey="IdTelco")]
		public EntitySet<SubTelco> SubTelcos1
		{
			get
			{
				return this._SubTelcos1;
			}
			set
			{
				this._SubTelcos1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Route_Telcos(Route_Telco entity)
		{
			this.SendPropertyChanging();
			entity.Telco = this;
		}
		
		private void detach_Route_Telcos(Route_Telco entity)
		{
			this.SendPropertyChanging();
			entity.Telco = null;
		}
		
		private void attach_SubTelcos(SubTelco entity)
		{
			this.SendPropertyChanging();
			entity.Telco = this;
		}
		
		private void detach_SubTelcos(SubTelco entity)
		{
			this.SendPropertyChanging();
			entity.Telco = null;
		}
		
		private void attach_SubTelcos1(SubTelco entity)
		{
			this.SendPropertyChanging();
			entity.Telco1 = this;
		}
		
		private void detach_SubTelcos1(SubTelco entity)
		{
			this.SendPropertyChanging();
			entity.Telco1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QueueService")]
	public partial class QueueService : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Source;
		
		private string _Dest;
		
		private string _TransID;
		
		private System.DateTime _TransTime;
		
		private string _User;
		
		private string _Password;
		
		private string _ProcessingCode;
		
		private int _Priority;
		
		private string _Content;
		
		private string _Receiver;
		
		private System.DateTime _DateCreate;
		
		private string _SMSID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnDestChanging(string value);
    partial void OnDestChanged();
    partial void OnTransIDChanging(string value);
    partial void OnTransIDChanged();
    partial void OnTransTimeChanging(System.DateTime value);
    partial void OnTransTimeChanged();
    partial void OnUserChanging(string value);
    partial void OnUserChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnProcessingCodeChanging(string value);
    partial void OnProcessingCodeChanged();
    partial void OnPriorityChanging(int value);
    partial void OnPriorityChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnReceiverChanging(string value);
    partial void OnReceiverChanged();
    partial void OnDateCreateChanging(System.DateTime value);
    partial void OnDateCreateChanged();
    partial void OnSMSIDChanging(string value);
    partial void OnSMSIDChanged();
    #endregion
		
		public QueueService()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(50)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dest", DbType="NVarChar(50)")]
		public string Dest
		{
			get
			{
				return this._Dest;
			}
			set
			{
				if ((this._Dest != value))
				{
					this.OnDestChanging(value);
					this.SendPropertyChanging();
					this._Dest = value;
					this.SendPropertyChanged("Dest");
					this.OnDestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransID", DbType="NVarChar(50)")]
		public string TransID
		{
			get
			{
				return this._TransID;
			}
			set
			{
				if ((this._TransID != value))
				{
					this.OnTransIDChanging(value);
					this.SendPropertyChanging();
					this._TransID = value;
					this.SendPropertyChanged("TransID");
					this.OnTransIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransTime", DbType="DateTime NOT NULL")]
		public System.DateTime TransTime
		{
			get
			{
				return this._TransTime;
			}
			set
			{
				if ((this._TransTime != value))
				{
					this.OnTransTimeChanging(value);
					this.SendPropertyChanging();
					this._TransTime = value;
					this.SendPropertyChanged("TransTime");
					this.OnTransTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="NVarChar(50)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this.OnUserChanging(value);
					this.SendPropertyChanging();
					this._User = value;
					this.SendPropertyChanged("User");
					this.OnUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessingCode", DbType="NVarChar(50)")]
		public string ProcessingCode
		{
			get
			{
				return this._ProcessingCode;
			}
			set
			{
				if ((this._ProcessingCode != value))
				{
					this.OnProcessingCodeChanging(value);
					this.SendPropertyChanging();
					this._ProcessingCode = value;
					this.SendPropertyChanged("ProcessingCode");
					this.OnProcessingCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receiver", DbType="NVarChar(50)")]
		public string Receiver
		{
			get
			{
				return this._Receiver;
			}
			set
			{
				if ((this._Receiver != value))
				{
					this.OnReceiverChanging(value);
					this.SendPropertyChanging();
					this._Receiver = value;
					this.SendPropertyChanged("Receiver");
					this.OnReceiverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreate", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreate
		{
			get
			{
				return this._DateCreate;
			}
			set
			{
				if ((this._DateCreate != value))
				{
					this.OnDateCreateChanging(value);
					this.SendPropertyChanging();
					this._DateCreate = value;
					this.SendPropertyChanged("DateCreate");
					this.OnDateCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSID", DbType="NVarChar(250)")]
		public string SMSID
		{
			get
			{
				return this._SMSID;
			}
			set
			{
				if ((this._SMSID != value))
				{
					this.OnSMSIDChanging(value);
					this.SendPropertyChanging();
					this._SMSID = value;
					this.SendPropertyChanged("SMSID");
					this.OnSMSIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Route")]
	public partial class Route : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private int _RouteNumber;
		
		private string _Code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnRouteNumberChanging(int value);
    partial void OnRouteNumberChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    #endregion
		
		public Route()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteNumber", DbType="Int NOT NULL")]
		public int RouteNumber
		{
			get
			{
				return this._RouteNumber;
			}
			set
			{
				if ((this._RouteNumber != value))
				{
					this.OnRouteNumberChanging(value);
					this.SendPropertyChanging();
					this._RouteNumber = value;
					this.SendPropertyChanged("RouteNumber");
					this.OnRouteNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Route_Telco")]
	public partial class Route_Telco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdTelco;
		
		private double _Price;
		
		private System.Nullable<int> _Route;
		
		private int _Ratio;
		
		private EntityRef<Telco> _Telco;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdTelcoChanging(int value);
    partial void OnIdTelcoChanged();
    partial void OnPriceChanging(double value);
    partial void OnPriceChanged();
    partial void OnRouteChanging(System.Nullable<int> value);
    partial void OnRouteChanged();
    partial void OnRatioChanging(int value);
    partial void OnRatioChanged();
    #endregion
		
		public Route_Telco()
		{
			this._Telco = default(EntityRef<Telco>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTelco", DbType="Int NOT NULL")]
		public int IdTelco
		{
			get
			{
				return this._IdTelco;
			}
			set
			{
				if ((this._IdTelco != value))
				{
					if (this._Telco.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTelcoChanging(value);
					this.SendPropertyChanging();
					this._IdTelco = value;
					this.SendPropertyChanged("IdTelco");
					this.OnIdTelcoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float NOT NULL")]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Route", DbType="Int")]
		public System.Nullable<int> Route
		{
			get
			{
				return this._Route;
			}
			set
			{
				if ((this._Route != value))
				{
					this.OnRouteChanging(value);
					this.SendPropertyChanging();
					this._Route = value;
					this.SendPropertyChanged("Route");
					this.OnRouteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ratio", DbType="Int NOT NULL")]
		public int Ratio
		{
			get
			{
				return this._Ratio;
			}
			set
			{
				if ((this._Ratio != value))
				{
					this.OnRatioChanging(value);
					this.SendPropertyChanging();
					this._Ratio = value;
					this.SendPropertyChanged("Ratio");
					this.OnRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Telco_Route_Telco", Storage="_Telco", ThisKey="IdTelco", OtherKey="Id", IsForeignKey=true)]
		public Telco Telco
		{
			get
			{
				return this._Telco.Entity;
			}
			set
			{
				Telco previousValue = this._Telco.Entity;
				if (((previousValue != value) 
							|| (this._Telco.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Telco.Entity = null;
						previousValue.Route_Telcos.Remove(this);
					}
					this._Telco.Entity = value;
					if ((value != null))
					{
						value.Route_Telcos.Add(this);
						this._IdTelco = value.Id;
					}
					else
					{
						this._IdTelco = default(int);
					}
					this.SendPropertyChanged("Telco");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubTelco")]
	public partial class SubTelco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdTelco;
		
		private string _StartPhone;
		
		private EntityRef<Telco> _Telco;
		
		private EntityRef<Telco> _Telco1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdTelcoChanging(System.Nullable<int> value);
    partial void OnIdTelcoChanged();
    partial void OnStartPhoneChanging(string value);
    partial void OnStartPhoneChanged();
    #endregion
		
		public SubTelco()
		{
			this._Telco = default(EntityRef<Telco>);
			this._Telco1 = default(EntityRef<Telco>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTelco", DbType="Int")]
		public System.Nullable<int> IdTelco
		{
			get
			{
				return this._IdTelco;
			}
			set
			{
				if ((this._IdTelco != value))
				{
					if ((this._Telco.HasLoadedOrAssignedValue || this._Telco1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTelcoChanging(value);
					this.SendPropertyChanging();
					this._IdTelco = value;
					this.SendPropertyChanged("IdTelco");
					this.OnIdTelcoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartPhone", DbType="VarChar(10)")]
		public string StartPhone
		{
			get
			{
				return this._StartPhone;
			}
			set
			{
				if ((this._StartPhone != value))
				{
					this.OnStartPhoneChanging(value);
					this.SendPropertyChanging();
					this._StartPhone = value;
					this.SendPropertyChanged("StartPhone");
					this.OnStartPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Telco_SubTelco", Storage="_Telco", ThisKey="IdTelco", OtherKey="Id", IsForeignKey=true)]
		public Telco Telco
		{
			get
			{
				return this._Telco.Entity;
			}
			set
			{
				Telco previousValue = this._Telco.Entity;
				if (((previousValue != value) 
							|| (this._Telco.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Telco.Entity = null;
						previousValue.SubTelcos.Remove(this);
					}
					this._Telco.Entity = value;
					if ((value != null))
					{
						value.SubTelcos.Add(this);
						this._IdTelco = value.Id;
					}
					else
					{
						this._IdTelco = default(Nullable<int>);
					}
					this.SendPropertyChanged("Telco");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Telco_SubTelco1", Storage="_Telco1", ThisKey="IdTelco", OtherKey="Id", IsForeignKey=true)]
		public Telco Telco1
		{
			get
			{
				return this._Telco1.Entity;
			}
			set
			{
				Telco previousValue = this._Telco1.Entity;
				if (((previousValue != value) 
							|| (this._Telco1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Telco1.Entity = null;
						previousValue.SubTelcos1.Remove(this);
					}
					this._Telco1.Entity = value;
					if ((value != null))
					{
						value.SubTelcos1.Add(this);
						this._IdTelco = value.Id;
					}
					else
					{
						this._IdTelco = default(Nullable<int>);
					}
					this.SendPropertyChanged("Telco1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MTQueueReport")]
	public partial class MTQueueReport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Source;
		
		private string _Dest;
		
		private string _TransID;
		
		private System.DateTime _TransTime;
		
		private string _User;
		
		private string _Password;
		
		private string _ProcessingCode;
		
		private int _Priority;
		
		private string _Content;
		
		private string _Receiver;
		
		private System.DateTime _DateCreate;
		
		private System.DateTime _TimeSend;
		
		private int _Status;
		
		private string _SMSID;
		
		private int _Result;
		
		private string _RouteName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnDestChanging(string value);
    partial void OnDestChanged();
    partial void OnTransIDChanging(string value);
    partial void OnTransIDChanged();
    partial void OnTransTimeChanging(System.DateTime value);
    partial void OnTransTimeChanged();
    partial void OnUserChanging(string value);
    partial void OnUserChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnProcessingCodeChanging(string value);
    partial void OnProcessingCodeChanged();
    partial void OnPriorityChanging(int value);
    partial void OnPriorityChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnReceiverChanging(string value);
    partial void OnReceiverChanged();
    partial void OnDateCreateChanging(System.DateTime value);
    partial void OnDateCreateChanged();
    partial void OnTimeSendChanging(System.DateTime value);
    partial void OnTimeSendChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnSMSIDChanging(string value);
    partial void OnSMSIDChanged();
    partial void OnResultChanging(int value);
    partial void OnResultChanged();
    partial void OnRouteNameChanging(string value);
    partial void OnRouteNameChanged();
    #endregion
		
		public MTQueueReport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(50)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dest", DbType="NVarChar(50)")]
		public string Dest
		{
			get
			{
				return this._Dest;
			}
			set
			{
				if ((this._Dest != value))
				{
					this.OnDestChanging(value);
					this.SendPropertyChanging();
					this._Dest = value;
					this.SendPropertyChanged("Dest");
					this.OnDestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransID", DbType="NVarChar(50)")]
		public string TransID
		{
			get
			{
				return this._TransID;
			}
			set
			{
				if ((this._TransID != value))
				{
					this.OnTransIDChanging(value);
					this.SendPropertyChanging();
					this._TransID = value;
					this.SendPropertyChanged("TransID");
					this.OnTransIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransTime", DbType="DateTime NOT NULL")]
		public System.DateTime TransTime
		{
			get
			{
				return this._TransTime;
			}
			set
			{
				if ((this._TransTime != value))
				{
					this.OnTransTimeChanging(value);
					this.SendPropertyChanging();
					this._TransTime = value;
					this.SendPropertyChanged("TransTime");
					this.OnTransTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="NVarChar(50)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this.OnUserChanging(value);
					this.SendPropertyChanging();
					this._User = value;
					this.SendPropertyChanged("User");
					this.OnUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessingCode", DbType="NVarChar(50)")]
		public string ProcessingCode
		{
			get
			{
				return this._ProcessingCode;
			}
			set
			{
				if ((this._ProcessingCode != value))
				{
					this.OnProcessingCodeChanging(value);
					this.SendPropertyChanging();
					this._ProcessingCode = value;
					this.SendPropertyChanged("ProcessingCode");
					this.OnProcessingCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receiver", DbType="NVarChar(50)")]
		public string Receiver
		{
			get
			{
				return this._Receiver;
			}
			set
			{
				if ((this._Receiver != value))
				{
					this.OnReceiverChanging(value);
					this.SendPropertyChanging();
					this._Receiver = value;
					this.SendPropertyChanged("Receiver");
					this.OnReceiverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreate", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreate
		{
			get
			{
				return this._DateCreate;
			}
			set
			{
				if ((this._DateCreate != value))
				{
					this.OnDateCreateChanging(value);
					this.SendPropertyChanging();
					this._DateCreate = value;
					this.SendPropertyChanged("DateCreate");
					this.OnDateCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeSend", DbType="DateTime NOT NULL")]
		public System.DateTime TimeSend
		{
			get
			{
				return this._TimeSend;
			}
			set
			{
				if ((this._TimeSend != value))
				{
					this.OnTimeSendChanging(value);
					this.SendPropertyChanging();
					this._TimeSend = value;
					this.SendPropertyChanged("TimeSend");
					this.OnTimeSendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSID", DbType="NVarChar(50)")]
		public string SMSID
		{
			get
			{
				return this._SMSID;
			}
			set
			{
				if ((this._SMSID != value))
				{
					this.OnSMSIDChanging(value);
					this.SendPropertyChanging();
					this._SMSID = value;
					this.SendPropertyChanged("SMSID");
					this.OnSMSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int NOT NULL")]
		public int Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteName", DbType="NVarChar(50)")]
		public string RouteName
		{
			get
			{
				return this._RouteName;
			}
			set
			{
				if ((this._RouteName != value))
				{
					this.OnRouteNameChanging(value);
					this.SendPropertyChanging();
					this._RouteName = value;
					this.SendPropertyChanged("RouteName");
					this.OnRouteNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MT")]
	public partial class MT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Source;
		
		private string _Dest;
		
		private string _TransID;
		
		private System.DateTime _TransTime;
		
		private string _User;
		
		private string _Password;
		
		private string _ProcessingCode;
		
		private int _Priority;
		
		private string _Content;
		
		private string _Receiver;
		
		private System.DateTime _DateCreate;
		
		private System.DateTime _TimeSend;
		
		private int _Status;
		
		private string _SMSID;
		
		private int _Result;
		
		private string _RouteName;
		
		private System.Nullable<int> _IdTelco;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnDestChanging(string value);
    partial void OnDestChanged();
    partial void OnTransIDChanging(string value);
    partial void OnTransIDChanged();
    partial void OnTransTimeChanging(System.DateTime value);
    partial void OnTransTimeChanged();
    partial void OnUserChanging(string value);
    partial void OnUserChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnProcessingCodeChanging(string value);
    partial void OnProcessingCodeChanged();
    partial void OnPriorityChanging(int value);
    partial void OnPriorityChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnReceiverChanging(string value);
    partial void OnReceiverChanged();
    partial void OnDateCreateChanging(System.DateTime value);
    partial void OnDateCreateChanged();
    partial void OnTimeSendChanging(System.DateTime value);
    partial void OnTimeSendChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnSMSIDChanging(string value);
    partial void OnSMSIDChanged();
    partial void OnResultChanging(int value);
    partial void OnResultChanged();
    partial void OnRouteNameChanging(string value);
    partial void OnRouteNameChanged();
    partial void OnIdTelcoChanging(System.Nullable<int> value);
    partial void OnIdTelcoChanged();
    #endregion
		
		public MT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(50)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dest", DbType="NVarChar(50)")]
		public string Dest
		{
			get
			{
				return this._Dest;
			}
			set
			{
				if ((this._Dest != value))
				{
					this.OnDestChanging(value);
					this.SendPropertyChanging();
					this._Dest = value;
					this.SendPropertyChanged("Dest");
					this.OnDestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransID", DbType="NVarChar(50)")]
		public string TransID
		{
			get
			{
				return this._TransID;
			}
			set
			{
				if ((this._TransID != value))
				{
					this.OnTransIDChanging(value);
					this.SendPropertyChanging();
					this._TransID = value;
					this.SendPropertyChanged("TransID");
					this.OnTransIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransTime", DbType="DateTime NOT NULL")]
		public System.DateTime TransTime
		{
			get
			{
				return this._TransTime;
			}
			set
			{
				if ((this._TransTime != value))
				{
					this.OnTransTimeChanging(value);
					this.SendPropertyChanging();
					this._TransTime = value;
					this.SendPropertyChanged("TransTime");
					this.OnTransTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="NVarChar(50)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this.OnUserChanging(value);
					this.SendPropertyChanging();
					this._User = value;
					this.SendPropertyChanged("User");
					this.OnUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessingCode", DbType="NVarChar(50)")]
		public string ProcessingCode
		{
			get
			{
				return this._ProcessingCode;
			}
			set
			{
				if ((this._ProcessingCode != value))
				{
					this.OnProcessingCodeChanging(value);
					this.SendPropertyChanging();
					this._ProcessingCode = value;
					this.SendPropertyChanged("ProcessingCode");
					this.OnProcessingCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receiver", DbType="NVarChar(50)")]
		public string Receiver
		{
			get
			{
				return this._Receiver;
			}
			set
			{
				if ((this._Receiver != value))
				{
					this.OnReceiverChanging(value);
					this.SendPropertyChanging();
					this._Receiver = value;
					this.SendPropertyChanged("Receiver");
					this.OnReceiverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreate", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreate
		{
			get
			{
				return this._DateCreate;
			}
			set
			{
				if ((this._DateCreate != value))
				{
					this.OnDateCreateChanging(value);
					this.SendPropertyChanging();
					this._DateCreate = value;
					this.SendPropertyChanged("DateCreate");
					this.OnDateCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeSend", DbType="DateTime NOT NULL")]
		public System.DateTime TimeSend
		{
			get
			{
				return this._TimeSend;
			}
			set
			{
				if ((this._TimeSend != value))
				{
					this.OnTimeSendChanging(value);
					this.SendPropertyChanging();
					this._TimeSend = value;
					this.SendPropertyChanged("TimeSend");
					this.OnTimeSendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSID", DbType="NVarChar(50)")]
		public string SMSID
		{
			get
			{
				return this._SMSID;
			}
			set
			{
				if ((this._SMSID != value))
				{
					this.OnSMSIDChanging(value);
					this.SendPropertyChanging();
					this._SMSID = value;
					this.SendPropertyChanged("SMSID");
					this.OnSMSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int NOT NULL")]
		public int Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteName", DbType="NVarChar(50)")]
		public string RouteName
		{
			get
			{
				return this._RouteName;
			}
			set
			{
				if ((this._RouteName != value))
				{
					this.OnRouteNameChanging(value);
					this.SendPropertyChanging();
					this._RouteName = value;
					this.SendPropertyChanged("RouteName");
					this.OnRouteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTelco", DbType="Int")]
		public System.Nullable<int> IdTelco
		{
			get
			{
				return this._IdTelco;
			}
			set
			{
				if ((this._IdTelco != value))
				{
					this.OnIdTelcoChanging(value);
					this.SendPropertyChanging();
					this._IdTelco = value;
					this.SendPropertyChanged("IdTelco");
					this.OnIdTelcoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
