//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSProcess.ServiceVP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVP.GatewaySoap")]
    public interface GatewaySoap {
        
        // CODEGEN: Generating message contract since element name src from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMT", ReplyAction="*")]
        SMSProcess.ServiceVP.SendMTResponse SendMT(SMSProcess.ServiceVP.SendMTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMT", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSProcess.ServiceVP.SendMTResponse> SendMTAsync(SMSProcess.ServiceVP.SendMTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMT", Namespace="http://tempuri.org/", Order=0)]
        public SMSProcess.ServiceVP.SendMTRequestBody Body;
        
        public SendMTRequest() {
        }
        
        public SendMTRequest(SMSProcess.ServiceVP.SendMTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string src;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dest;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string msgbody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string requestid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        public SendMTRequestBody() {
        }
        
        public SendMTRequestBody(string src, string dest, string msgbody, string requestid, string username, string password) {
            this.src = src;
            this.dest = dest;
            this.msgbody = msgbody;
            this.requestid = requestid;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMTResponse", Namespace="http://tempuri.org/", Order=0)]
        public SMSProcess.ServiceVP.SendMTResponseBody Body;
        
        public SendMTResponse() {
        }
        
        public SendMTResponse(SMSProcess.ServiceVP.SendMTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMTResult;
        
        public SendMTResponseBody() {
        }
        
        public SendMTResponseBody(int SendMTResult) {
            this.SendMTResult = SendMTResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GatewaySoapChannel : SMSProcess.ServiceVP.GatewaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatewaySoapClient : System.ServiceModel.ClientBase<SMSProcess.ServiceVP.GatewaySoap>, SMSProcess.ServiceVP.GatewaySoap {
        
        public GatewaySoapClient() {
        }
        
        public GatewaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GatewaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMSProcess.ServiceVP.SendMTResponse SMSProcess.ServiceVP.GatewaySoap.SendMT(SMSProcess.ServiceVP.SendMTRequest request) {
            return base.Channel.SendMT(request);
        }
        
        public int SendMT(string src, string dest, string msgbody, string requestid, string username, string password) {
            SMSProcess.ServiceVP.SendMTRequest inValue = new SMSProcess.ServiceVP.SendMTRequest();
            inValue.Body = new SMSProcess.ServiceVP.SendMTRequestBody();
            inValue.Body.src = src;
            inValue.Body.dest = dest;
            inValue.Body.msgbody = msgbody;
            inValue.Body.requestid = requestid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            SMSProcess.ServiceVP.SendMTResponse retVal = ((SMSProcess.ServiceVP.GatewaySoap)(this)).SendMT(inValue);
            return retVal.Body.SendMTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSProcess.ServiceVP.SendMTResponse> SMSProcess.ServiceVP.GatewaySoap.SendMTAsync(SMSProcess.ServiceVP.SendMTRequest request) {
            return base.Channel.SendMTAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSProcess.ServiceVP.SendMTResponse> SendMTAsync(string src, string dest, string msgbody, string requestid, string username, string password) {
            SMSProcess.ServiceVP.SendMTRequest inValue = new SMSProcess.ServiceVP.SendMTRequest();
            inValue.Body = new SMSProcess.ServiceVP.SendMTRequestBody();
            inValue.Body.src = src;
            inValue.Body.dest = dest;
            inValue.Body.msgbody = msgbody;
            inValue.Body.requestid = requestid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SMSProcess.ServiceVP.GatewaySoap)(this)).SendMTAsync(inValue);
        }
    }
}
