//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWSVietinbank.ServiceVietinbank {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVietinbank.VB2B_SMSSoap")]
    public interface VB2B_SMSSoap {
        
        // CODEGEN: Generating message contract since element name xmlres from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMTRes", ReplyAction="*")]
        TestWSVietinbank.ServiceVietinbank.ReceiveMTResResponse ReceiveMTRes(TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMTRes", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWSVietinbank.ServiceVietinbank.ReceiveMTResResponse> ReceiveMTResAsync(TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMTResRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMTRes", Namespace="http://tempuri.org/", Order=0)]
        public TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequestBody Body;
        
        public ReceiveMTResRequest() {
        }
        
        public ReceiveMTResRequest(TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMTResRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlres;
        
        public ReceiveMTResRequestBody() {
        }
        
        public ReceiveMTResRequestBody(string xmlres) {
            this.xmlres = xmlres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMTResResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMTResResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWSVietinbank.ServiceVietinbank.ReceiveMTResResponseBody Body;
        
        public ReceiveMTResResponse() {
        }
        
        public ReceiveMTResResponse(TestWSVietinbank.ServiceVietinbank.ReceiveMTResResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMTResResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReceiveMTResResult;
        
        public ReceiveMTResResponseBody() {
        }
        
        public ReceiveMTResResponseBody(string ReceiveMTResResult) {
            this.ReceiveMTResResult = ReceiveMTResResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VB2B_SMSSoapChannel : TestWSVietinbank.ServiceVietinbank.VB2B_SMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VB2B_SMSSoapClient : System.ServiceModel.ClientBase<TestWSVietinbank.ServiceVietinbank.VB2B_SMSSoap>, TestWSVietinbank.ServiceVietinbank.VB2B_SMSSoap {
        
        public VB2B_SMSSoapClient() {
        }
        
        public VB2B_SMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VB2B_SMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VB2B_SMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VB2B_SMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWSVietinbank.ServiceVietinbank.ReceiveMTResResponse TestWSVietinbank.ServiceVietinbank.VB2B_SMSSoap.ReceiveMTRes(TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequest request) {
            return base.Channel.ReceiveMTRes(request);
        }
        
        public string ReceiveMTRes(string xmlres) {
            TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequest inValue = new TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequest();
            inValue.Body = new TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequestBody();
            inValue.Body.xmlres = xmlres;
            TestWSVietinbank.ServiceVietinbank.ReceiveMTResResponse retVal = ((TestWSVietinbank.ServiceVietinbank.VB2B_SMSSoap)(this)).ReceiveMTRes(inValue);
            return retVal.Body.ReceiveMTResResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWSVietinbank.ServiceVietinbank.ReceiveMTResResponse> TestWSVietinbank.ServiceVietinbank.VB2B_SMSSoap.ReceiveMTResAsync(TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequest request) {
            return base.Channel.ReceiveMTResAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWSVietinbank.ServiceVietinbank.ReceiveMTResResponse> ReceiveMTResAsync(string xmlres) {
            TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequest inValue = new TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequest();
            inValue.Body = new TestWSVietinbank.ServiceVietinbank.ReceiveMTResRequestBody();
            inValue.Body.xmlres = xmlres;
            return ((TestWSVietinbank.ServiceVietinbank.VB2B_SMSSoap)(this)).ReceiveMTResAsync(inValue);
        }
    }
}
