//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSProcess.ServiceVietinbank {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVietinbank.VB2B_SMSSoap")]
    public interface VB2B_SMSSoap {
        
        // CODEGEN: Generating message contract since element name xmlres from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMTResBDSD", ReplyAction="*")]
        SMSProcess.ServiceVietinbank.ReceiveMTResBDSDResponse ReceiveMTResBDSD(SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMTResBDSD", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSProcess.ServiceVietinbank.ReceiveMTResBDSDResponse> ReceiveMTResBDSDAsync(SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequest request);
        
        // CODEGEN: Generating message contract since element name xmlres from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMTResOTP", ReplyAction="*")]
        SMSProcess.ServiceVietinbank.ReceiveMTResOTPResponse ReceiveMTResOTP(SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMTResOTP", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSProcess.ServiceVietinbank.ReceiveMTResOTPResponse> ReceiveMTResOTPAsync(SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMTResBDSDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMTResBDSD", Namespace="http://tempuri.org/", Order=0)]
        public SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequestBody Body;
        
        public ReceiveMTResBDSDRequest() {
        }
        
        public ReceiveMTResBDSDRequest(SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMTResBDSDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlres;
        
        public ReceiveMTResBDSDRequestBody() {
        }
        
        public ReceiveMTResBDSDRequestBody(string xmlres) {
            this.xmlres = xmlres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMTResBDSDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMTResBDSDResponse", Namespace="http://tempuri.org/", Order=0)]
        public SMSProcess.ServiceVietinbank.ReceiveMTResBDSDResponseBody Body;
        
        public ReceiveMTResBDSDResponse() {
        }
        
        public ReceiveMTResBDSDResponse(SMSProcess.ServiceVietinbank.ReceiveMTResBDSDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMTResBDSDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReceiveMTResBDSDResult;
        
        public ReceiveMTResBDSDResponseBody() {
        }
        
        public ReceiveMTResBDSDResponseBody(string ReceiveMTResBDSDResult) {
            this.ReceiveMTResBDSDResult = ReceiveMTResBDSDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMTResOTPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMTResOTP", Namespace="http://tempuri.org/", Order=0)]
        public SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequestBody Body;
        
        public ReceiveMTResOTPRequest() {
        }
        
        public ReceiveMTResOTPRequest(SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMTResOTPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlres;
        
        public ReceiveMTResOTPRequestBody() {
        }
        
        public ReceiveMTResOTPRequestBody(string xmlres) {
            this.xmlres = xmlres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMTResOTPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMTResOTPResponse", Namespace="http://tempuri.org/", Order=0)]
        public SMSProcess.ServiceVietinbank.ReceiveMTResOTPResponseBody Body;
        
        public ReceiveMTResOTPResponse() {
        }
        
        public ReceiveMTResOTPResponse(SMSProcess.ServiceVietinbank.ReceiveMTResOTPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMTResOTPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReceiveMTResOTPResult;
        
        public ReceiveMTResOTPResponseBody() {
        }
        
        public ReceiveMTResOTPResponseBody(string ReceiveMTResOTPResult) {
            this.ReceiveMTResOTPResult = ReceiveMTResOTPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VB2B_SMSSoapChannel : SMSProcess.ServiceVietinbank.VB2B_SMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VB2B_SMSSoapClient : System.ServiceModel.ClientBase<SMSProcess.ServiceVietinbank.VB2B_SMSSoap>, SMSProcess.ServiceVietinbank.VB2B_SMSSoap {
        
        public VB2B_SMSSoapClient() {
        }
        
        public VB2B_SMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VB2B_SMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VB2B_SMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VB2B_SMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMSProcess.ServiceVietinbank.ReceiveMTResBDSDResponse SMSProcess.ServiceVietinbank.VB2B_SMSSoap.ReceiveMTResBDSD(SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequest request) {
            return base.Channel.ReceiveMTResBDSD(request);
        }
        
        public string ReceiveMTResBDSD(string xmlres) {
            SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequest inValue = new SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequest();
            inValue.Body = new SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequestBody();
            inValue.Body.xmlres = xmlres;
            SMSProcess.ServiceVietinbank.ReceiveMTResBDSDResponse retVal = ((SMSProcess.ServiceVietinbank.VB2B_SMSSoap)(this)).ReceiveMTResBDSD(inValue);
            return retVal.Body.ReceiveMTResBDSDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSProcess.ServiceVietinbank.ReceiveMTResBDSDResponse> SMSProcess.ServiceVietinbank.VB2B_SMSSoap.ReceiveMTResBDSDAsync(SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequest request) {
            return base.Channel.ReceiveMTResBDSDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSProcess.ServiceVietinbank.ReceiveMTResBDSDResponse> ReceiveMTResBDSDAsync(string xmlres) {
            SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequest inValue = new SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequest();
            inValue.Body = new SMSProcess.ServiceVietinbank.ReceiveMTResBDSDRequestBody();
            inValue.Body.xmlres = xmlres;
            return ((SMSProcess.ServiceVietinbank.VB2B_SMSSoap)(this)).ReceiveMTResBDSDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMSProcess.ServiceVietinbank.ReceiveMTResOTPResponse SMSProcess.ServiceVietinbank.VB2B_SMSSoap.ReceiveMTResOTP(SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequest request) {
            return base.Channel.ReceiveMTResOTP(request);
        }
        
        public string ReceiveMTResOTP(string xmlres) {
            SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequest inValue = new SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequest();
            inValue.Body = new SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequestBody();
            inValue.Body.xmlres = xmlres;
            SMSProcess.ServiceVietinbank.ReceiveMTResOTPResponse retVal = ((SMSProcess.ServiceVietinbank.VB2B_SMSSoap)(this)).ReceiveMTResOTP(inValue);
            return retVal.Body.ReceiveMTResOTPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSProcess.ServiceVietinbank.ReceiveMTResOTPResponse> SMSProcess.ServiceVietinbank.VB2B_SMSSoap.ReceiveMTResOTPAsync(SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequest request) {
            return base.Channel.ReceiveMTResOTPAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSProcess.ServiceVietinbank.ReceiveMTResOTPResponse> ReceiveMTResOTPAsync(string xmlres) {
            SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequest inValue = new SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequest();
            inValue.Body = new SMSProcess.ServiceVietinbank.ReceiveMTResOTPRequestBody();
            inValue.Body.xmlres = xmlres;
            return ((SMSProcess.ServiceVietinbank.VB2B_SMSSoap)(this)).ReceiveMTResOTPAsync(inValue);
        }
    }
}
